#MakeFile to build and deploy the Sample US CENSUS Name Data using ajax
# For CSC3004 Software Development

USER= Game2

all: PutHTML

PutHTML:
		cp Level1.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Level2.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Home.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Login1.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp LoginStyle.css /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Game.css /var/www/html/class/ssd/$(USER)/LGAttempt3/


		echo "Current contents of your HTML directory: "
		ls -l /var/www/html/class/ssd/$(USER)/LGAttempt3/