#MakeFile to build and deploy the Sample US CENSUS Name Data using ajax
# For CSC3004 Software Development

USER= Game2

all: PutHTML

PutHTML:
		cp Connection.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Game.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Home.php /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp Login1.html /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp LoginStyle.css /var/www/html/class/ssd/$(USER)/LGAttempt3/
		cp validate.js /var/www/html/class/ssd/$(USER)/LGAttempt3/

		echo "Current contents of your HTML directory: "
		ls -l /var/www/html/class/ssd/$(USER)/LGAttempt3/
