USER= Game2

all: PutHTML

PutHTML:
	cp getQuestion.php /var/www/html/class/ssd/$(USER)/UniQuReq/
	cp display.html /var/www/html/class/ssd/$(USER)/UniQuReq/

	echo "Current contents of your HTML directory: "
	ls -l /var/www/html/class/ssd/$(USER)/UniQuReq/