#MakeFile to build and deploy the Sample US CENSUS Name Data using ajax
# For CSC3004 Software Development

USER= Game2

all: PutHTML

PutHTML:
		cp -r  DuckHunt-JS-master /var/www/html/class/ssd/$(USER)/DuckHuntTest
		cp -r  space-jump-master /var/www/html/class/ssd/$(USER)/DuckHuntTest
